#
# To use:
#   conda env create -f environment.yml
#   conda activate imgstitch
#
name: imgstitch
dependencies:
  - python >= 3.10
  - pillow >= 9.3.0
  - numpy >= 1.23.5
  - scipy >= 1.9.3
# For testing
  - pytest >= 7
  - pytest-cov >= 3
